{% set name = "pydorado" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydorado-{{ version }}.tar.gz
  sha256: f2eae7ec3c4ae1a15dfd31cd3de345d4ad9af9ca327b36fbfebe12492d740977

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - scipy
    - future
    - tqdm

test:
  imports:
    - dorado
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/passaH2O/dorado
  summary: dorado - Lagrangian particle routing routine via weighted random walks
  license: MIT
  license_file: LICENSE
  doc_url: https://passah2o.github.io/dorado
  dev_url: https://github.com/passaH2O/dorado

extra:
  recipe-maintainers:
    - elbeejay
    - wrightky
